[package]
name = "store-derive"
edition = "2024"
version.workspace = true

[dependencies]
proc-macro2 = "1.0.106"
quote = "1.0.44"
syn = { version = "1.0.109", features = ["full", "derive", "extra-traits"] }
itertools.workspace = true

[lints]
workspace = true


[lib]
proc-macro = true
