[package]
name = "runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
blobs.workspace = true
burn.workspace = true
models.workspace = true
serde.workspace = true
types.workspace = true
async-trait.workspace = true
bytes.workspace = true
tonic.workspace = true
bcs.workspace = true
tokio.workspace = true
tower-http.workspace = true
prost.workspace = true
object_store.workspace = true
memmap2.workspace = true

[dev-dependencies]
tokio.workspace = true

[build-dependencies]
tonic-build.workspace = true
tonic-prost-build.workspace = true

[lints]
workspace = true
