[package]
name = "inference"
version = "0.1.0"
edition = "2024"

[dependencies]
blobs.workspace = true
burn.workspace = true
models.workspace = true
serde.workspace = true

[dev-dependencies]

[build-dependencies]
tonic-build.workspace = true
tonic-prost-build.workspace = true

[lints]
workspace = true
