[package]
name = "runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
blobs.workspace = true
burn.workspace = true
models.workspace = true
object_store.workspace = true
types.workspace = true
async-trait.workspace = true
tokio.workspace = true
anyhow.workspace = true
aes.workspace = true
ctr.workspace = true

[build-dependencies]
tonic-build.workspace = true
tonic-prost-build.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
url.workspace = true

[features]
default = []
cuda = ["burn/cuda"]
rocm = ["burn/rocm"]
tch = ["burn/tch"]

[lints]
workspace = true
