[package]
name = "arrgen"
version = "0.1.0"
edition = "2024"

[lib]
name = "arrgen"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3.workspace = true
rand.workspace = true
ndarray.workspace = true
ndarray-rand.workspace = true
numpy.workspace = true

[lints]
workspace = true
