[package]
name = "store"
edition = "2024"
version.workspace = true

[dependencies]
rocksdb = { version = "0.22.0", default-features = false, features = [
    "snappy",
    "lz4",
    "zstd",
    "zlib",
    "multi-threaded-cf",
] }
serde.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["full", "test-util"] }
tracing.workspace = true
backoff = { version = "0.4.0", features = [
    "futures",
    "futures-core",
    "pin-project-lite",
    "tokio",
    "tokio_1",
] }
bcs.workspace = true
bincode = "1.3.3"
# collectable.workspace = true
fastcrypto.workspace = true
uint = "0.9.5"
store-derive.workspace = true
fdlimit = "0.2.1"
once_cell = { version = "1.21.3" }
tempfile.workspace = true
tap.workspace = true
rstest = "0.16.0"

[dev-dependencies]
eyre.workspace = true

[lints]
workspace = true
