[package]
name = "store"
edition = "2024"
version.workspace = true

[dependencies]
rocksdb = { version = "0.22.0", default-features = false, features = [
    "snappy",
    "lz4",
    "zstd",
    "zlib",
    "multi-threaded-cf",
] }
serde.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["full", "test-util"] }
tracing.workspace = true
backoff.workspace = true
bcs.workspace = true
bincode.workspace = true
# collectable.workspace = true
fastcrypto.workspace = true
uint.workspace = true
store-derive.workspace = true
fdlimit.workspace = true
tempfile.workspace = true
tap.workspace = true
rstest.workspace = true

[dev-dependencies]
eyre.workspace = true

[lints]
workspace = true
