[package]
name = "types"
edition = "2024"
version.workspace = true

[dependencies]
protocol-config.workspace = true
serde.workspace = true
rand.workspace = true
fastcrypto.workspace = true
anyhow.workspace = true
eyre.workspace = true
bcs.workspace = true
serde_repr.workspace = true
thiserror.workspace = true
multiaddr.workspace = true
tracing.workspace = true
tonic.workspace = true
tokio.workspace = true
tap.workspace = true
async-trait.workspace = true
nonempty.workspace = true
parking_lot.workspace = true
tower.workspace = true
ed25519.workspace = true
hyper.workspace = true
hyper-util.workspace = true
tokio-rustls.workspace = true
tower-http.workspace = true
hyper-rustls.workspace = true
cfg-if.workspace = true
base64.workspace = true
itertools.workspace = true
futures.workspace = true
tracing-subscriber.workspace = true
tempfile.workspace = true
prost.workspace = true
bytes.workspace = true
strum_macros.workspace = true
strum.workspace = true
tonic-rustls.workspace = true
http.workspace = true
pin-project-lite.workspace = true
url.workspace = true
store.workspace = true
object_store.workspace = true
burn.workspace = true
arrgen.workspace = true
clap.workspace = true
soma-http.workspace = true
byteorder = "1.5.0"
serde_yaml = "0.8.26"
serde_with = { version = "3.16", features = ["schemars_0_8"] }
derive_more = "0.99.20"
schemars = { version = "0.8.22", features = ["either"] }
hex = "0.4.3"
static_assertions = "1.1.0"
serde-name = "0.2.1"
enum_dispatch = "^0.3"
roaring = "0.10.12"
rustls.workspace = true
dirs = "4.0.0"
camino = "1.2.2"
webpki.workspace = true
x509-parser.workspace = true
reqwest = { version = "0.12", features = ["http2", "json", "rustls-tls"] }
axum.workspace = true
axum-server.workspace = true
rcgen = "0.13.2"
tower-layer = "0.3.3"
http-body = "1"
http-body-util = "0.1"
once_cell = "1.21.3"
lru = "0.10"
csv = "1.4.0"

[lints]
workspace = true
