[package]
name = "types"
edition = "2021"
version.workspace = true

[dependencies]
serde.workspace = true
rand.workspace = true
fastcrypto.workspace = true
anyhow.workspace = true
eyre.workspace = true
bcs.workspace = true
serde_repr.workspace = true
thiserror.workspace = true
multiaddr.workspace = true
tracing.workspace = true
tonic.workspace = true
tokio.workspace = true
tap.workspace = true
async-trait.workspace = true
nonempty.workspace = true
parking_lot.workspace = true
tower.workspace = true
ed25519.workspace = true
hyper.workspace = true
hyper-util.workspace = true
tokio-rustls.workspace = true
tower-http.workspace = true
hyper-rustls.workspace = true
cfg-if.workspace = true
base64.workspace = true
itertools.workspace = true
futures.workspace = true
tracing-subscriber.workspace = true
tempfile.workspace = true
prost.workspace = true
bytes.workspace = true
soma-tls.workspace = true
strum_macros.workspace = true
vdf.workspace = true
strum.workspace = true
tokio-util.workspace = true
quick_cache.workspace = true
arc-swap.workspace = true
tonic-rustls.workspace = true
http.workspace = true
pin-project-lite.workspace = true
serde_urlencoded.workspace = true
url.workspace = true
store.workspace = true
serde_yaml = "0.8.26"
serde_with = { version = "3.8", features = ["schemars_0_8"] }
derive_more = "0.99.17"
schemars = { version = "0.8.21", features = ["either"] }
hex = "0.4.3"
static_assertions = "1.1.0"
serde-name = "0.2.1"
enum_dispatch = "^0.3"
roaring = "0.10.6"
rustls = { version = "0.23.12", default-features = false, features = [
  "std",
  "tls12",
  "ring",
] }
futures-util = { version = "0.3" }
tokio-retry = "0.3"
webpki = { version = "0.102", package = "rustls-webpki", features = [
  "alloc",
  "std",
] }
x509-parser = "0.16.0"
reqwest = { version = "0.12", default_features = false, features = [
  "http2",
  "json",
  "rustls-tls",
] }
axum = { version = "0.7.5", default-features = false, features = [
  "tokio",
  "http1",
  "http2",
  "json",
  "matched-path",
  "original-uri",
  "form",
  "query",
  "ws",
] }
axum-server = { git = "https://github.com/bmwill/axum-server.git", rev = "f44323e271afdd1365fd0c8b0a4c0bbdf4956cb7", version = "0.6", default-features = false, features = [
  "tls-rustls",
] }
rcgen = "0.13.1"
tower-layer = "0.3.2"
http-body = "1.0.1"
http-body-util = "0.1.2"
once_cell = "1.20.2"
rstest = "0.16.0"

[build-dependencies]
tonic-build.workspace = true
