[package]
name = "protocol-config-macros"
edition = "2024"
version.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.106"
syn = "2.0.114"
quote = "1.0.44"

[lints]
workspace = true
