[package]
name = "shard"
version = "0.1.0"
edition = "2021"

[dependencies]
# internal deps
macros.workspace = true
# external deps
tokio.workspace = true
serde.workspace = true
fastcrypto.workspace = true
bcs.workspace = true
# bs58.workspace = true
enum_dispatch.workspace = true
bytes.workspace = true
strum_macros.workspace = true
thiserror.workspace = true
base64.workspace = true
multiaddr.workspace = true
eyre.workspace = true
tracing.workspace = true
rand.workspace = true
serde_repr.workspace = true
url.workspace = true

[lints]
workspace = true
