[package]
name = "probes"
edition = "2024"
version.workspace = true

[dependencies]
num-traits.workspace = true

[dependencies.burn]
workspace = true
features = ["ndarray", "autodiff"]

[lints]
workspace = true
