[package]
name = "soma-keys"
edition = "2024"
version.workspace = true

[dependencies]
fastcrypto.workspace = true
bip32.workspace = true
slip10_ed25519.workspace = true
tiny-bip39.workspace = true
types = { path = "../types", default-features = false }
enum_dispatch.workspace = true
serde.workspace = true
serde_json.workspace = true
rand.workspace = true
regex.workspace = true
anyhow.workspace = true
async-trait.workspace = true
signature = "1.6.4"
colored = "2.2.0"
tokio.workspace = true

[lints]
workspace = true
