[package]
name = "soma-keys"
edition = "2024"
version.workspace = true

[dependencies]
fastcrypto.workspace = true
bip32.workspace = true
tiny-bip39.workspace = true
slip10_ed25519.workspace = true
strum_macros.workspace = true
thiserror.workspace = true
types.workspace = true
enum_dispatch.workspace = true
serde.workspace = true
serde_json.workspace = true
rand.workspace = true
regex.workspace = true

[lints]
workspace = true
