[alias]
t = "llvm-cov nextest"
d = "doc --document-private-items"
do = "doc --open --document-private-items"
cov = "llvm-cov nextest --open"

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-undefined", "-C", "link-arg=dynamic_lookup"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-undefined", "-C", "link-arg=dynamic_lookup"]

[build]
rustflags = [
    "-C",
    "link-args=-Wl,-rpath,/Library/Developer/CommandLineTools/Library/Frameworks",
]
