[package]
name = "test-encoder-cluster"
edition = "2021"
version.workspace = true

[dependencies]
tokio.workspace = true
tracing.workspace = true
anyhow.workspace = true
encoder.workspace = true
shared.workspace = true
futures.workspace = true
rand.workspace = true
msim.workspace = true
soma-network.workspace = true
soma-tls.workspace = true
objects.workspace = true
fastcrypto.workspace = true

[lints]
workspace = true
