[package]
name = "intelligence"
version = "0.1.0"
edition = "2024"

[features]
safetensors = []

[dependencies]


[dev-dependencies]


[build-dependencies]
tonic-build.workspace = true
tonic-prost-build.workspace = true

[lints]
workspace = true
