[package]
name = "soma-tls"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow.workspace = true
arc-swap.workspace = true
ed25519.workspace = true
pkcs8.workspace = true
rcgen.workspace = true
rustls.workspace = true
webpki.workspace = true
x509-parser.workspace = true
tracing.workspace = true

fastcrypto.workspace = true

# reqwest support
reqwest.workspace = true

# Axum support
axum.workspace = true
axum-server.workspace = true
tokio-rustls.workspace = true
tower-layer.workspace = true
tokio.workspace = true

[dev-dependencies]
rand.workspace = true

[lints]
workspace = true
