[project]
name = "soma-probes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flax>=0.7.2",
    "safetensors>=0.6.2",
]

[build-system]
requires = ["uv_build>=0.8.22,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "arrgen",
    "pytest>=8.3.5",
    "safetensors>=0.6.2",
]

[tool.uv.sources]
arrgen = { workspace = true }

# [build-system]
# requires = ["hatchling"]
# build-backend = "hatchling.build"
