[package]
name = "soma-sdk"
version = "0.1.0"
edition = "2024"

[lib]
name = "soma_sdk"
crate-type = ["cdylib"]

[dependencies]
pyo3.workspace = true
pyo3-async-runtimes = { workspace = true, features = ["tokio-runtime"] }
tokio = { workspace = true, features = ["rt-multi-thread"] }
sdk.workspace = true
types.workspace = true
soma-keys.workspace = true
rpc.workspace = true
serde_json.workspace = true
serde.workspace = true
anyhow.workspace = true
bcs.workspace = true
futures.workspace = true
hex.workspace = true
url.workspace = true

[lints]
workspace = true
