[package]
name = "soma-sdk"
version = "0.1.4"
edition = "2021"

[lib]
name = "soma_sdk"
crate-type = ["cdylib"]

[dependencies]
pyo3.workspace = true
pyo3-async-runtimes = { workspace = true, features = ["tokio-runtime"] }
tokio = { workspace = true, features = ["rt-multi-thread"] }
sdk = { path = "../sdk", default-features = false, features = ["grpc-services", "proxy"] }
types = { path = "../types", default-features = false }
faucet = { path = "../faucet", default-features = false }
rpc = { path = "../rpc", default-features = false }
serde.workspace = true
bcs.workspace = true
futures.workspace = true
hex.workspace = true
url.workspace = true
pythonize.workspace = true

[lints]
workspace = true
