[package]
name = "soma-sdk"
version = "0.1.7"
edition = "2024"

[lib]
name = "soma_sdk"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3.workspace = true
pyo3-async-runtimes = { workspace = true, features = ["tokio-runtime"] }
tokio = { workspace = true, features = ["rt-multi-thread"] }
sdk = { path = "../sdk", default-features = false, features = [
    "grpc-services",
    "tls",
] }
types = { path = "../types", default-features = false }
rpc = { path = "../rpc", default-features = false }
serde.workspace = true
bcs.workspace = true
futures.workspace = true
fastcrypto.workspace = true
hex.workspace = true
url.workspace = true
pythonize.workspace = true

[dev-dependencies]
test-cluster.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
soma-keys.workspace = true


[lints]
workspace = true
