[package]
name = "soma-sdk"
version = "0.1.2"
edition = "2024"

[lib]
name = "soma_sdk"
crate-type = ["cdylib"]

[dependencies]
pyo3.workspace = true
pyo3-async-runtimes = { workspace = true, features = ["tokio-runtime"] }
tokio = { workspace = true, features = ["rt-multi-thread"] }
sdk = { path = "../sdk", default-features = false }
types = { path = "../types", default-features = false }
soma-keys.workspace = true
rpc = { path = "../rpc", default-features = false }
serde_json.workspace = true
serde.workspace = true
anyhow.workspace = true
bcs.workspace = true
futures.workspace = true
hex.workspace = true
url.workspace = true

[lints]
workspace = true
