[package]
name = "sync"
edition = "2021"
version.workspace = true

[dependencies]
types.workspace = true
tracing.workspace = true
parking_lot.workspace = true
tokio.workspace = true
futures.workspace = true
tonic.workspace = true
utils.workspace = true
rand.workspace = true
fastcrypto.workspace = true
bcs.workspace = true
tap.workspace = true
anyhow.workspace = true
bytes.workspace = true
itertools.workspace = true
async-trait.workspace = true
data-ingestion.workspace = true
tonic-rustls.workspace = true

[build-dependencies]
tonic-build.workspace = true

[lints]
workspace = true
