[package]
name = "vdf"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
fastcrypto.workspace = true
num-bigint.workspace = true
num-traits.workspace = true
num-integer.workspace = true
num-prime.workspace = true 
rand.workspace = true
rand_chacha.workspace = true
serde.workspace = true
bcs.workspace = true
lazy_static.workspace = true

[dev-dependencies]
hex.workspace = true
criterion.workspace = true
rand.workspace = true
num-bigint-dig.workspace = true
