[package]
name = "soma-http"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
soma-tls.workspace = true
bytes.workspace = true
http.workspace = true
http-body.workspace = true
http-body-util.workspace = true
hyper.workspace = true
hyper-util.workspace = true
pin-project-lite.workspace = true
socket2.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tower.workspace = true
tracing.workspace = true
rustls.workspace = true
# TLS support
tokio-rustls.workspace = true

[dev-dependencies]
axum.workspace = true
reqwest.workspace = true
