[package]
name = "soma-python"
version = "0.1.0"
edition = "2021"

[lib]
name = "soma"
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
encoder.workspace = true
numpy.workspace = true


[dependencies.pyo3]
workspace = true
features = ["extension-module","abi3-py38"]

[build-dependencies]
pyo3-build-config.workspace = true

[lints]
workspace = true

